Repository APISuite/apisuite-fe, pull requests merged in 2021-05, with the labels that each got.

#404 test: update cypress test suite
  .babelrc
  .eslintrc
  cypress.json
  cypress/fixtures/apis.json
  cypress/fixtures/profile.json
  cypress/fixtures/settings.json
  cypress/integration/000-landing.spec.ts
  cypress/integration/001-signin.spec.ts
  cypress/integration/Sandbox/inform-flow.spec.ts
  cypress/plugins/index.ts
  cypress/support/commands.js
  cypress/support/commands.ts
  cypress/support/index.d.ts
  cypress/support/index.ts
  cypress/tsconfig.json
  generate_envfile.sh
  install_dependencies.sh
  package-lock.json
  package.json
  run_tests.sh
  src/components/CookiesBanner/CookiesBanner.tsx
  src/components/Footer/Footer.tsx
  src/components/Navigation/Navigation.tsx
  src/components/SignInForm/SignInForm.tsx
  src/testIds.ts
Labels: internal

#409 perf: update fe-base and theme mapping changes
  cypress/fixtures/settings.json
  package-lock.json
  package.json
  src/components/APICatalog/styles.ts
  src/components/ActionsCatalog/styles.ts
  src/components/ApplicationsModal/ApplicationsModal.tsx
  src/components/ApplicationsModal/styles.ts
  src/components/Carousel/styles.ts
  src/components/CookiesBanner/styles.ts
  src/components/CustomizableDialog/styles.ts
  src/components/Footer/Footer.tsx
  src/components/Footer/styles.ts
  src/components/FormCard/styles.ts
  src/components/GreetingCard/GreetingCard.tsx
  src/components/GreetingCard/styles.ts
  src/components/GreetingCard/types.d.ts
  src/components/InvitationForm/styles.ts
  src/components/Navigation/styles.ts
  src/components/Notice/styles.ts
  src/components/Notification/styles.ts
  src/components/NotificationCard/styles.ts
  src/components/SSOForm/styles.ts
  src/components/SignInForm/styles.ts
  src/components/SignUpForm/styles.ts
  src/components/SubscriptionsModal/styles.ts
  src/components/SubscriptionsTable/styles.ts
  src/language/styles.ts
  src/pages/APIDetails/styles.ts
  src/pages/APIProducts/styles.ts
  src/pages/Applications/styles.ts
  src/pages/Dashboard/Dashboard.tsx
  src/pages/Dashboard/styles.ts
  src/pages/Instructions/styles.ts
  src/pages/Organisation/styles.ts
  src/pages/PasswordRecovery/styles.ts
  src/pages/Profile/Profile.tsx
  src/pages/Profile/styles.ts
  src/pages/Sandbox/Sandbox.tsx
  src/pages/Sandbox/styles.ts
  src/pages/Security/styles.ts
  src/pages/SignUpConfirmation/styles.ts
  src/pages/Subscriptions/styles.ts
  src/pages/TeamPage/TeamPage.tsx
  src/pages/TeamPage/styles.ts
  webpack.config.dev.js
Labels: performance improvement

#419 chore: sync staging with develop
  package-lock.json
  package.json
  src/components/InvitationForm/InvitationForm.tsx
  src/components/InvitationForm/LoadingView.tsx
  src/components/InvitationForm/styles.ts
  src/language/translations/en-US.json
  src/pages/SignInOrUp/SignInOrUp.tsx
  src/pages/SignInOrUp/styles.ts
  src/store/auth/actions/invitation.ts
  src/store/auth/actions/types.d.ts
  src/store/auth/middleware.ts
  src/store/auth/sagas.ts
Labels: internal

#414 fix(APIProducts): extra `v` char when no version available
  src/components/APICatalog/APICatalog.tsx
  src/pages/APIProducts/APIProducts.tsx
Labels: bug

#415 fix(translations): typo
  src/language/translations/en-US.json
Labels: bug

#420 fix(ApplicationsModal): locked copy CTA's
  README.md
  cypress.json
  package.json
  src/components/ApplicationsModal/ApplicationsModal.tsx
  src/components/ApplicationsModal/styles.ts
  ssl/localhost.develop.apisuite.io-key.pem
  ssl/localhost.develop.apisuite.io.pem
  webpack.config.dev.js
Labels: bug

#424 fix: translations typos and space incorrections
  src/language/translations/en-US.json
  src/pages/Dashboard/Dashboard.tsx
  src/pages/Sandbox/Sandbox.tsx
Labels: bug

#423 fix(request-access): add request access feedback
  src/language/translations/en-US.json
  src/store/applications/sagas.ts
Labels: bug
